[package]
name = "macmon"
version = "0.3.0"
edition = "2021"

[lints.rust]
non_camel_case_types = "allow"
unused_assignments = "allow"
unreachable_code = "allow"

[profile.release]
panic = "abort"
strip = false

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
core-foundation = "0.10.0"
libc = "0.2.159"
ratatui = { version = "0.28.1", features = ["serde"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
