[package]
name = "macmon"
version = "0.2.2"
edition = "2021"

[lints.rust]
non_camel_case_types = "allow"
unused_assignments = "allow"
unreachable_code = "allow"

[profile.release]
panic = "abort"
strip = false

[dependencies]
clap = {version = "4.5.19", features = ["derive"]}
core-foundation = "0.10.0"
libc = "0.2.159"
ratatui = "0.28.1"
serde_json = "1.0.128"
